name: Build React app and deploy to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:    
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Install build tools
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="/opt/buildhome/.bun/bin:$PATH"
          bun install

      - name: Build
        run: bun vite build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist directory
          path: 'dist'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
